"""Initial migration

Revision ID: 88502d60997b
Revises: 18de5a398e9a
Create Date: 2025-01-14 12:32:46.157677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88502d60997b'
down_revision = '18de5a398e9a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('max_attendees', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('scheduled', 'ongoing', 'completed', 'canceled', name='event_statuses'), nullable=True),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('attendee',
    sa.Column('attendee_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('check_in_status', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.event_id'], ),
    sa.PrimaryKeyConstraint('attendee_id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attendee')
    op.drop_table('event')
    # ### end Alembic commands ###
